### ISSUE TITLE
Using 'wait_interactive()' with 'direct_view.map_async()'

### ISSUE THREAD

**Issue by vik748** [ipython/ipyparallel#419] opened 2020-07-26 04:00 UTC
I have a simple code which is trying to perform some analysis on about 2000 images.  Since I have a cpu with 16 processor. Each operation is take about 10 secs and I'd like to be able to monitor the progress.  Here is a snippet:
```
tic = time.time()

ipp_client = ipp.Client()
ipp_dview = ipp_client[:]
curr_dir = os.path.dirname(__file__)
ipp_dview.execute("import sys,os; \
                   from feat_detector_comparisions_helper import process_image_contrasts".format(curr_dir, curr_dir))

ipp_dview.push({'contrast_adj_factors': contrast_adj_factors, 'base_settings': base_settings,
                'mask_folder': mask_folder, 'ctrst_img_output_folder': ctrst_img_output_folder})

process_img_lam = lambda img_name:process_image_contrasts(img_name, contrast_adj_factors=contrast_adj_factors, mask_folder=mask_folder,
                                                          ctrst_img_output_folder = ctrst_img_output_folder, base_settings=base_settings)

img_df_list = ipp_dview.map_async(process_img_lam, image_names)
img_df_list.wait_interactive() # wait for all jobs to finish
```

Given that this job is expected to take 4-5 hrs, I'd like to be able to monitor the progress.  I see that there is a wait_interactive() which is supposed to display the progress.  However when I run it it only shows shows me 16 tasks instead for the full 2000. Also the output just stays at 0/16 for most of the duration of the job.
```
   0/16 tasks finished after   1287 s
```
Is there another way that can give me a better progress updated on how many of the cumulative map iterations have been performed.  

Here I am using a direct view since I didn't see a way to send all the variables I need to the load balanced view.  Any help is appreciated.

Cheers,
Vik

**Comment by minrk** [comment] 2021-06-04 13:25
Closing as duplicate of #217

Short answer from over there: the task count is the number of 'execution requests' not items in the sequence. When you use a DirectView is always one per engine. Using a DirectView also means you won't get any partial results back until an engine completes its whole chunk, if that's valuable to you. If you switch to LoadBalancedView, you will get one task per map item, and the wait_interactive number will be updated as results come in.

**Closed by minrk** 2021-06-04 13:25 UTC
