### ISSUE TITLE
8.2.1: pep517 build is failing

### ISSUE THREAD

**Issue by kloczek** [ipython/ipyparallel#688] opened 2022-04-05 20:34 UTC
I'm using as input source autogenerated from git tag by github tar ball.
Looks like pep517 build is failing.
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 7.80s.
yarn run v1.21.1
$ jlpm run build:lib && jlpm run build:labextension
$ tsc
$ jupyter labextension build .
Building extension in .

Compilation starting…

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/NormalModule.js:946:10)
    at /home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/NormalModule.js:755:11)
    at /home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
An error occurred.
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/node_modules/@jupyterlab/builder/lib/build-labextension.js', '--core-path', '/usr/lib/python3.8/site-packages/jupyterlab/staging', '/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1']' returned non-zero exit status 1.
See the log file for details:  /tmp/jupyterlab-debug-yhz1ohtz.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 77, in <module>
    builder()
  File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/setupbase.py", line 232, in builder
    run(npm_cmd + ["run", build_cmd], cwd=node_package)
  File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.2.1/setupbase.py", line 296, in run
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/jlpm', 'run', 'build:prod']' returned non-zero exit status 1.

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by minrk** [comment] 2022-04-06 06:38
Closing as duplicate of #653 . As discussed there, I believe this is an issue with the host installation of nodejs. The error is an in internal, low-level nodejs API call.

**Closed by minrk** 2022-04-06 06:38 UTC
