### ISSUE TITLE
Checking ssh availability of machines and launching ipcluster from python

### ISSUE THREAD

**Issue by dompas** [ipython/ipyparallel#369] opened 2019-05-22 19:02 UTC
This topic is related to the topic #22. I am a post graduate student member of the Signal Processing Laboratory (LPS - USP - Brazil) where we have a Beowulf cluster that is under constant change, so it is hard to keep changing the configuration file to only use the available machines. In addition to that we also would like to start the ipcluster from python (like suggested in topic #22 ). I have reached a solution that solves these two problems, by checking the avilables machines, their cores numbers and changing the configuration file and them launching the ipcluster from python. The code that I used was:

```
import spur
import re
import os
import ipyparallel as ipp
import time

def start_cluster(machines_ips): #machines_ips should have strings with the ips of the machines you want to use

    available_machines = {}

    for i in machines:
        try:
            shell = spur.SshShell(hostname=i) #Tries to connect to the machine
            with shell:
                result = shell.run(["nproc", "--all"]) #Requests the number of processors of the machine
            available_machines[i] = int(re.findall(r'\d+',result.output.decode("utf-8"))[0]) - 1 #Saves the number of processor minus one which is kept for house keeping
        except spur.ssh.ConnectionError:
            pass #If the conection fails the machine is not added on the ipcluster
    print(available_machines) #Print the machines that are going to be used for reference
    home = os.path.expanduser('~') #Aquire the home directory
    path_config = '/.ipython/profile_lpscluster/' #The directory of the configuration file
    config_file_name = 'ipcluster_config.py' #Name of the configuration file

    config_file_text = ''

    with open(home+path_config+config_file_name,'r') as f:  #Read the text of the file
        config_file_text = f.read()

    with open(home+path_config+config_file_name,'w') as f: #Overwrite the file, changing the text that defines the machines used
        f.write(re.sub(r'c.SSHEngineSetLauncher.engines = {.+}','c.SSHEngineSetLauncher.engines = '+str(available_machines),config_file_text))

    shell = spur.LocalShell() #Starts a local shell
    result = shell.spawn(["ipcluster","start","--profile=lpscluster"]) #Run the command to start the ipcluster
    time.sleep(15) #Wait 15 seconds for the cluster start
    rc = ipp.Client(profile='lpscluster') #Start the client using the profile
    return rc[:] #Return all engines
```
I am sharing the code in case someone is interested.

**Comment by minrk** [comment] 2021-06-04 09:31
Thanks for your sample! I'm finally working on an API for this in #463. I'm going to close this as a duplicate of a few other issues, but thanks for the reference for what might be needed in the SSH case!

**Closed by minrk** 2021-06-04 09:31 UTC
